name: projet_b3
description: B3 project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_map_location_marker: any
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  graph_collection: ^2.1.0
  graphs: ^2.3.0
  slugify: ^2.0.0
  google_fonts: ^4.0.4
  app_usage: ^2.1.1
  flutter_svg_provider: ^1.0.3

  provider: ^6.0.5
  extended_image: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/map/
  uses-material-design: true
  fonts:
    - family: custom_icons
      fonts:
        - asset: fonts/custom_icons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
