/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'custom_icons';
  static const String? _kFontPkg = null;

  static const IconData spider = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData butterfly = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frog = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snake = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appareilPhoto = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloche_03 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData croix = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engrenage = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feminin = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information02 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData masculin = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification02 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData param_tres = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cadrePhoto = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil02 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recentrer = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recherche02 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retour = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
