/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons3 {
  CustomIcons3._();

  static const _kFontFam = 'custom_icons3';
  static const String? _kFontPkg = null;

  static const IconData notification_02 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData param_tres = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil_02 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recentrer = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recherche_02 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retour = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData serpent = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ajout_photo = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appareil_photo = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData araign_e = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloche_03 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData croix = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engrenage = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feminin = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grenouille = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_02 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insecte = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData masculin = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_plus = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validate = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
