/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';
import 'package:projet_b3/Themes/colors.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData profil_02 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil_03 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quiet_01 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData respect_01 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_01 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_01 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snake_01 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spider_01 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_01 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_02 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_03 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman_01 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_01 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_01 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_02 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_03 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData center_01 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_01 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_01 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog_01 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_01 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_01 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_02 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_03 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
 static const IconData heart_01 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frog_01 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_01 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_02 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_03 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_01 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_02 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_03 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insect_01 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_01 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_glass_01 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_glass_02 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_glass_03 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man_01 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_01 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_02 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_03 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_01 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_plus_01 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_01 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_01 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil_01 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static Stack mapShadow = Stack(
    alignment: Alignment.center,
    children: const [
      Icon(CustomIcons.map_01, size: 30, color: Color(0xFFF4EADC)),
      Icon(CustomIcons.map_02, size: 30, color: Color(0xFFF8F1E4),),
      Icon(CustomIcons.map_03, size: 30,),
    ],
  );

  static Stack glassShadow = Stack(
    alignment: Alignment.center,
    children: const [
      Icon(CustomIcons.m_glass_03, size: 30, color: Color(0xFFF4EADC),),
      Icon(CustomIcons.m_glass_02, size: 30, color: Color(0xFFF8F1E4),),
      Icon(CustomIcons.m_glass_01, size: 30),
    ],
  );

  static Stack glassShadowColor = Stack(
    alignment: Alignment.center,
    children: const [
      Icon(CustomIcons.m_glass_03, size: 70, color: Color(0xFFF4EADC),),
      Icon(CustomIcons.m_glass_02, size: 70, color: Color(0xFFF8F1E4),),
      Icon(CustomIcons.m_glass_01, size: 70, color: black,),
    ],
  );

  static Stack infoShadow = Stack(
    alignment: Alignment.center,
    children: const [
      Icon(CustomIcons.info_03, size: 30, color: Color(0xFFF4EADC),),
      Icon(CustomIcons.info_02, size: 30, color: Color(0xFFF8F1E4),),
      Icon(CustomIcons.info_01, size: 30),
    ],
  );

  static Stack bellShadow = Stack(
    alignment: Alignment.center,
    children: const [
      Icon(CustomIcons.bell_03, size: 17, color: Color(0xFFF4EADC)),
      Icon(CustomIcons.bell_02, size: 17, color: Color(0xFFF8F1E4),),
      Icon(CustomIcons.bell_01, size: 17,),
    ],
  );

}
